fix bin/show_changes for invalid CVS headers

diff --git a/bin/show_changes b/bin/show_changes
--- a/bin/show_changes
+++ b/bin/show_changes
@@ -71,8 +71,22 @@ then
 		*) die 2 "diff failed with exit code $?" ;;
 	esac
 else
-	overlay_revision="$(awk '/# \$Header: / { print $4; exit }' "$file")" || \
-		die 3 "failed to pull revision from cvs header in overlay file"
+	overlay_revision="$(awk -v file="$file" '
+
+		/# \$Header: / {
+			if ( $3 == "/var/cvsroot/gentoo-x86/" file ",v" ) {
+				print $4
+			}
+			exit;
+		}
+	
+		' "$file")" || die 3 "couldn't get CVS revision of '$file'"
+
+	if ! [[ "$overlay_revision" ]]
+	then
+		overlay_revision="1.1"
+		echo "'$file' in overlay has broken CVS header, please fix it"
+	fi
 
 	pushd >/dev/null "$EMULTILIB_CVS_TREE" || \
 		die 2 "pushd '$EMULTILIB_CVS_TREE' failed"
