synced net-libs/xulrunner via auto-sync

diff --git a/doc/patches/net-libs/xulrunner/xulrunner-1.9.2.8.ebuild.patch b/doc/patches/net-libs/xulrunner/xulrunner-1.9.2.8.ebuild.patch
--- a/doc/patches/net-libs/xulrunner/xulrunner-1.9.2.8.ebuild.patch
+++ b/doc/patches/net-libs/xulrunner/xulrunner-1.9.2.8.ebuild.patch
@@ -1,17 +1,17 @@
---- /usr/portage/net-libs/xulrunner/xulrunner-1.9.1.8.ebuild	2010-03-04 19:23:04.000000000 +0100
-+++ ./net-libs/xulrunner/xulrunner-1.9.1.8.ebuild	2010-03-14 04:41:16.000000000 +0100
-@@ -216,7 +216,7 @@
+--- /usr/portage/net-libs/xulrunner/xulrunner-1.9.2.8.ebuild	2010-07-25 17:36:43.000000000 +0200
++++ ./net-libs/xulrunner/xulrunner-1.9.2.8.ebuild	2010-07-25 21:32:10.000000000 +0200
+@@ -201,7 +201,7 @@
  
  	# env.d file for ld search path
  	dodir /etc/env.d
--	echo "LDPATH=${MOZLIBDIR}" > "${D}"/etc/env.d/08xulrunner || die "env.d failed"
-+	echo "LDPATH=${MOZLIBDIR}" > "${D}"/etc/env.d/08xulrunner-${ABI} || die "env.d failed"
+-	echo "LDPATH=${EPREFIX}/${MOZLIBDIR}" > "${ED}"/etc/env.d/08xulrunner || die "env.d failed"
++	echo "LDPATH=${EPREFIX}/${MOZLIBDIR}" > "${ED}"/etc/env.d/08xulrunner-${ABI} || die "env.d failed"
  
  	# Add our defaults to xulrunner and out of firefox
  	cp "${FILESDIR}"/xulrunner-default-prefs.js \
-@@ -227,6 +227,11 @@
- 		java-pkg_regjar "${D}/${SDKDIR}/lib/MozillaGlue.jar"
- 		java-pkg_regjar "${D}/${SDKDIR}/lib/MozillaInterfaces.jar"
+@@ -214,20 +214,27 @@
+ 		java-pkg_regjar "${ED}/${SDKDIR}/lib/MozillaGlue.jar"
+ 		java-pkg_regjar "${ED}/${SDKDIR}/lib/MozillaInterfaces.jar"
  	fi
 +
 +	# each ABI should generate exactly one /etc/gre.d/*.system.conf file
@@ -21,10 +21,6 @@
  }
  
  pkg_postinst() {
-@@ -238,18 +243,20 @@
- 		python_mod_optimize "${MOZLIBDIR}/python"
- 	fi
- 
 -	ewarn "If firefox fails to start with \"failed to load xpcom\", run revdep-rebuild"
 -	ewarn "If that does not fix the problem, rebuild dev-libs/nss"
 -	ewarn "Try dev-util/lafilefixer if you get build failures related to .la files"
@@ -35,8 +31,9 @@
 -	einfo "having to go through and enable the basics."
 -
 -	einfo
--	ewarn "Please remember to rebuild your browser(s) after update to prevent an xpcom error."
--	ewarn "This bump is needed in order to bring icecat to the tree to replace iceweasel useflag."
+-	ewarn "Any package that requires xulrunner:1.9 slot could and most likely will"
+-	ewarn "have issues. These issues should be reported to maintainer, and mozilla herd"
+-	ewarn "should be cc'd on the bug report. Thank you anarchy@gentoo.org ."
 +	if is_final_abi ; then
 +		ewarn "If firefox fails to start with \"failed to load xpcom\", run revdep-rebuild"
 +		ewarn "If that does not fix the problem, rebuild dev-libs/nss"
@@ -46,11 +43,10 @@
 +		einfo "All prefs can be overridden by the user. The preferences are to make"
 +		einfo "use of xulrunner out of the box on an average system without the user"
 +		einfo "having to go through and enable the basics."
-+		
++
 +		einfo
-+		ewarn "Please remember to rebuild your browser(s) after update to prevent an xpcom error."
-+		ewarn "This bump is needed in order to bring icecat to the tree to replace iceweasel useflag."
++		ewarn "Any package that requires xulrunner:1.9 slot could and most likely will"
++		ewarn "have issues. These issues should be reported to maintainer, and mozilla herd"
++		ewarn "should be cc'd on the bug report. Thank you anarchy@gentoo.org ."
 +	fi
  }
- 
- pkg_postrm() {
