replaced the portageq call with hardcoded values

diff --git a/sys-apps/abi-wrapper/files/abi-wrapper b/sys-apps/abi-wrapper/files/abi-wrapper
--- a/sys-apps/abi-wrapper/files/abi-wrapper
+++ b/sys-apps/abi-wrapper/files/abi-wrapper
@@ -1,16 +1,13 @@
 #!/bin/bash
-# ${PN}-config is a link to this abi-wrapper on multilib-systems to
-# assure options like --libs return the correct ABI-specific values.
-# This must match the multilib-behaviour of the set profile!
 
 if [[ -n ${ABI} ]]; then
 	abi=${ABI}
 elif [[ -n ${DEFAULT_ABI} ]]; then
 	abi=${DEFAULT_ABI}
 else 
-	# we're called from outside portage, so try default first
-	abis=$(portageq envvar DEFAULT_ABI MULTILIB_ABIS)
-	for abi in ${abis}; do
+	# we're called from outside portage, so use the hardcoded abi list
+	hardcoded_abis=="PLACEHOLDER_FOR_HARDCODED_ABIS"
+	for abi in ${hardcoded_abis}; do
 		[[ -f ${0}-${abi} ]] && break
 		unset abi
 	done
@@ -23,7 +20,7 @@ else
 		LINK_TARGET="$(readlink ${0})"
 		exec ${LINK_TARGET} "${@}"
 	else
-		echo "${0}: abi-wrapper-config couldn't find script for current abi" >&2
+		echo "${0}: abi-wrapper couldn't find an executable for current abi ${abi}" >&2
 		exit 1
 	fi
 fi
